name: chgk_wheel_flutter
description: chgk wheel

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  arrow_path: ^1.0.0
  cupertino_icons: ^0.1.3
  audioplayers: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/whirligig.mp3
